global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'surgeshield_api'
    dns_sd_configs:
      - names:
          - 'tasks.api'
          - 'tasks.surgeshield_api'
        type: 'A'
        port: 3000

  - job_name: 'surgeshield_worker'
    dns_sd_configs:
      - names:
          - 'tasks.worker'
          - 'tasks.surgeshield_worker'
        type: 'A'
        port: 3001

  - job_name: 'autoscaler'
    static_configs:
      - targets: ['autoscaler:9091']
